-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module GraphQL.Interface.StudyPlanSegment exposing (Fragments, code, fragments, id, maybeFragments, name, slug)

import GraphQL.InputObject
import GraphQL.Interface
import GraphQL.Object
import GraphQL.Scalar
import GraphQL.ScalarCodecs
import GraphQL.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (FragmentSelectionSet(..), SelectionSet(..))
import Json.Decode as Decode


type alias Fragments decodesTo =
    { onStudyPlanGroup : SelectionSet decodesTo GraphQL.Object.StudyPlanGroup
    , onStudyPlanTopic : SelectionSet decodesTo GraphQL.Object.StudyPlanTopic
    , onStudyPlanSection : SelectionSet decodesTo GraphQL.Object.StudyPlanSection
    , onStudyPlanTarget : SelectionSet decodesTo GraphQL.Object.StudyPlanTarget
    }


{-| Build an exhaustive selection of type-specific fragments.
-}
fragments :
    Fragments decodesTo
    -> SelectionSet decodesTo GraphQL.Interface.StudyPlanSegment
fragments selections =
    Object.exhuastiveFragmentSelection
        [ Object.buildFragment "StudyPlanGroup" selections.onStudyPlanGroup
        , Object.buildFragment "StudyPlanTopic" selections.onStudyPlanTopic
        , Object.buildFragment "StudyPlanSection" selections.onStudyPlanSection
        , Object.buildFragment "StudyPlanTarget" selections.onStudyPlanTarget
        ]


{-| Can be used to create a non-exhuastive set of fragments by using the record
update syntax to add `SelectionSet`s for the types you want to handle.
-}
maybeFragments : Fragments (Maybe decodesTo)
maybeFragments =
    { onStudyPlanGroup = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onStudyPlanTopic = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onStudyPlanSection = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onStudyPlanTarget = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    }


id : SelectionSet GraphQL.ScalarCodecs.Id GraphQL.Interface.StudyPlanSegment
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (GraphQL.ScalarCodecs.codecs |> GraphQL.Scalar.unwrapCodecs |> .codecId |> .decoder)


code : SelectionSet String GraphQL.Interface.StudyPlanSegment
code =
    Object.selectionForField "String" "code" [] Decode.string


slug : SelectionSet String GraphQL.Interface.StudyPlanSegment
slug =
    Object.selectionForField "String" "slug" [] Decode.string


name : SelectionSet (Maybe String) GraphQL.Interface.StudyPlanSegment
name =
    Object.selectionForField "(Maybe String)" "name" [] (Decode.string |> Decode.nullable)
