-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module GraphQL.Object.Family exposing (childs, id, name, parents)

import GraphQL.InputObject
import GraphQL.Interface
import GraphQL.Object
import GraphQL.Scalar
import GraphQL.ScalarCodecs
import GraphQL.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet GraphQL.ScalarCodecs.Id GraphQL.Object.Family
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (GraphQL.ScalarCodecs.codecs |> GraphQL.Scalar.unwrapCodecs |> .codecId |> .decoder)


name : SelectionSet String GraphQL.Object.Family
name =
    Object.selectionForField "String" "name" [] Decode.string


parents : SelectionSet decodesTo GraphQL.Object.ParentProfile -> SelectionSet (List (Maybe decodesTo)) GraphQL.Object.Family
parents object_ =
    Object.selectionForCompositeField "parents" [] object_ (identity >> Decode.nullable >> Decode.list)


childs : SelectionSet decodesTo GraphQL.Object.ChildProfile -> SelectionSet (List (Maybe decodesTo)) GraphQL.Object.Family
childs object_ =
    Object.selectionForCompositeField "childs" [] object_ (identity >> Decode.nullable >> Decode.list)
