-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module GraphQL.Object.StudyPlanGroup exposing (id, name, plan, topics)

import GraphQL.InputObject
import GraphQL.Interface
import GraphQL.Object
import GraphQL.Scalar
import GraphQL.ScalarCodecs
import GraphQL.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet GraphQL.ScalarCodecs.Id GraphQL.Object.StudyPlanGroup
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (GraphQL.ScalarCodecs.codecs |> GraphQL.Scalar.unwrapCodecs |> .codecId |> .decoder)


name : SelectionSet (Maybe String) GraphQL.Object.StudyPlanGroup
name =
    Object.selectionForField "(Maybe String)" "name" [] (Decode.string |> Decode.nullable)


topics : SelectionSet decodesTo GraphQL.Object.StudyPlanTopic -> SelectionSet (List (Maybe decodesTo)) GraphQL.Object.StudyPlanGroup
topics object_ =
    Object.selectionForCompositeField "topics" [] object_ (identity >> Decode.nullable >> Decode.list)


plan : SelectionSet decodesTo GraphQL.Object.StudyPlan -> SelectionSet decodesTo GraphQL.Object.StudyPlanGroup
plan object_ =
    Object.selectionForCompositeField "plan" [] object_ identity
