-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module GraphQL.Object.StudyPlanTarget exposing (code, id, name, next, prev, section, slug)

import GraphQL.InputObject
import GraphQL.Interface
import GraphQL.Object
import GraphQL.Scalar
import GraphQL.ScalarCodecs
import GraphQL.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet GraphQL.ScalarCodecs.Id GraphQL.Object.StudyPlanTarget
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (GraphQL.ScalarCodecs.codecs |> GraphQL.Scalar.unwrapCodecs |> .codecId |> .decoder)


code : SelectionSet String GraphQL.Object.StudyPlanTarget
code =
    Object.selectionForField "String" "code" [] Decode.string


slug : SelectionSet String GraphQL.Object.StudyPlanTarget
slug =
    Object.selectionForField "String" "slug" [] Decode.string


name : SelectionSet (Maybe String) GraphQL.Object.StudyPlanTarget
name =
    Object.selectionForField "(Maybe String)" "name" [] (Decode.string |> Decode.nullable)


section : SelectionSet decodesTo GraphQL.Object.StudyPlanSection -> SelectionSet decodesTo GraphQL.Object.StudyPlanTarget
section object_ =
    Object.selectionForCompositeField "section" [] object_ identity


next : SelectionSet decodesTo GraphQL.Object.StudyPlanGroup -> SelectionSet (Maybe decodesTo) GraphQL.Object.StudyPlanTarget
next object_ =
    Object.selectionForCompositeField "next" [] object_ (identity >> Decode.nullable)


prev : SelectionSet decodesTo GraphQL.Object.StudyPlanGroup -> SelectionSet (Maybe decodesTo) GraphQL.Object.StudyPlanTarget
prev object_ =
    Object.selectionForCompositeField "prev" [] object_ (identity >> Decode.nullable)
