-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module GraphQL.Interface exposing (Node(..), UserProfile(..))


type Node
    = Node


type UserProfile
    = UserProfile
