-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module GraphQL.Interface exposing (IterableStudyPlanSegment(..), Node(..), StudyPlanSegment(..), UserProfile(..))


type IterableStudyPlanSegment
    = IterableStudyPlanSegment


type Node
    = Node


type StudyPlanSegment
    = StudyPlanSegment


type UserProfile
    = UserProfile
