-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module GraphQL.Object exposing (ChildProfile(..), Family(..), NodeConnection(..), NodeEdge(..), PageInfo(..), ParentProfile(..), StudyPlan(..), StudyPlanGroup(..), StudyPlanSection(..), StudyPlanTarget(..), StudyPlanTopic(..))


type ChildProfile
    = ChildProfile


type Family
    = Family


type NodeConnection
    = NodeConnection


type NodeEdge
    = NodeEdge


type PageInfo
    = PageInfo


type ParentProfile
    = ParentProfile


type StudyPlan
    = StudyPlan


type StudyPlanGroup
    = StudyPlanGroup


type StudyPlanSection
    = StudyPlanSection


type StudyPlanTarget
    = StudyPlanTarget


type StudyPlanTopic
    = StudyPlanTopic
