-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module GraphQL.ScalarCodecs exposing (DateTime, Id, codecs)

import GraphQL.Scalar exposing (defaultCodecs)
import Json.Decode as Decode exposing (Decoder)


type alias DateTime =
    GraphQL.Scalar.DateTime


type alias Id =
    GraphQL.Scalar.Id


codecs : GraphQL.Scalar.Codecs DateTime Id
codecs =
    GraphQL.Scalar.defineCodecs
        { codecDateTime = defaultCodecs.codecDateTime
        , codecId = defaultCodecs.codecId
        }
