-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module GraphQL.Union exposing (StudyPlanSearchResult(..), StudyPlanSegments(..))


type StudyPlanSearchResult
    = StudyPlanSearchResult


type StudyPlanSegments
    = StudyPlanSegments
